# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SyncSchema

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class End(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = End()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEnd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # End
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # End
    def Session(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def EndStart(builder):
    builder.StartObject(1)

def Start(builder):
    EndStart(builder)

def EndAddSession(builder, session):
    builder.PrependUint64Slot(0, session, 0)

def AddSession(builder, session):
    EndAddSession(builder, session)

def EndEnd(builder):
    return builder.EndObject()

def End(builder):
    return EndEnd(builder)
