# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SyncSchema

class MessageType(object):
    NONE = 0
    Data = 1
    Start = 2
    StartAck = 3
    End = 4
    EndAck = 5
    ReqRet = 6
