# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SyncSchema

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Pair(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Pair()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPair(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Pair
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Pair
    def Begin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Pair
    def End(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def PairStart(builder):
    builder.StartObject(2)

def Start(builder):
    PairStart(builder)

def PairAddBegin(builder, begin):
    builder.PrependUint64Slot(0, begin, 0)

def AddBegin(builder, begin):
    PairAddBegin(builder, begin)

def PairAddEnd(builder, end):
    builder.PrependUint64Slot(1, end, 0)

def AddEnd(builder, end):
    PairAddEnd(builder, end)

def PairEnd(builder):
    return builder.EndObject()

def End(builder):
    return PairEnd(builder)
