# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SyncSchema

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReqRet(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReqRet()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReqRet(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReqRet
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReqRet
    def Seq(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Wazuh.SyncSchema.Pair import Pair
            obj = Pair()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ReqRet
    def SeqLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ReqRet
    def SeqIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # ReqRet
    def Session(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def ReqRetStart(builder):
    builder.StartObject(2)

def Start(builder):
    ReqRetStart(builder)

def ReqRetAddSeq(builder, seq):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(seq), 0)

def AddSeq(builder, seq):
    ReqRetAddSeq(builder, seq)

def ReqRetStartSeqVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSeqVector(builder, numElems):
    return ReqRetStartSeqVector(builder, numElems)

def ReqRetAddSession(builder, session):
    builder.PrependUint64Slot(1, session, 0)

def AddSession(builder, session):
    ReqRetAddSession(builder, session)

def ReqRetEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReqRetEnd(builder)
