# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SyncSchema

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StartAck(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StartAck()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStartAck(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StartAck
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StartAck
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # StartAck
    def Session(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def StartAckStart(builder):
    builder.StartObject(2)

def Start(builder):
    StartAckStart(builder)

def StartAckAddStatus(builder, status):
    builder.PrependInt8Slot(0, status, 0)

def AddStatus(builder, status):
    StartAckAddStatus(builder, status)

def StartAckAddSession(builder, session):
    builder.PrependUint64Slot(1, session, 0)

def AddSession(builder, session):
    StartAckAddSession(builder, session)

def StartAckEnd(builder):
    return builder.EndObject()

def End(builder):
    return StartAckEnd(builder)
